### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by aps2201** [ldelossa/way-shell#5]
I'm using Fedora 39 sway spin and after creating the container using toolbox it gives me a make: *** [Makefile:13: run] Error 139. Can't seem to figure out the problem.

**Comment by lidgnulinux** [comment]
I'm also facing error, I'm using alpine linux : 
```
$ make
glib-compile-resources --generate-source --target src/gresources.c gresources.xml
glib-compile-resources --generate-header --target src/gresources.h gresources.xml
gcc -I/usr/include/libadwaita-1 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/us
r/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/
freetype2 -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -mfpmath=sse -m
sse -msse2 -I/usr/include/libupower-glib -I/usr/include/wireplumber-0.4 -I/usr/includ
e/spa-0.2 -I/usr/include/json-glib-1.0 -I/usr/include/libnm -I/usr/include/glib-2.0 -
I/usr/lib/glib-2.0/include -I/usr/include/webp -I/usr/include/libpng16 -I/usr/include
/pixman-1 -I/usr/include/fribidi -I/usr/include/appstream -I/usr/include/pipewire-0.3
 -D_REENTRANT -pthread -I/usr/include/libmount -I/usr/include/blkid -g3 -Wall   -c -o
 src/main.o src/main.c
In file included from src/./services/wireplumber_service.h:3,
                 from src/main.c:16:
/usr/include/sys/cdefs.h:4:2: warning: #warning usage of non-standard #include <sys/c
defs.h> is deprecated [-Wcpp]
    4 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^~~~~~~
src/main.c: In function 'activate':
src/main.c:33:13: warning: unused variable 'error' [-Wunused-variable]
   33 |     GError *error;
      |             ^~~~~
gcc -I/usr/include/libadwaita-1 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/us
r/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/
freetype2 -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -mfpmath=sse -m
sse -msse2 -I/usr/include/libupower-glib -I/usr/include/wireplumber-0.4 -I/usr/includ
e/spa-0.2 -I/usr/include/json-glib-1.0 -I/usr/include/libnm -I/usr/include/glib-2.0 -
I/usr/lib/glib-2.0/include -I/usr/include/webp -I/usr/include/libpng16 -I/usr/include
/pixman-1 -I/usr/include/fribidi -I/usr/include/appstream -I/usr/include/pipewire-0.3
 -D_REENTRANT -pthread -I/usr/include/libmount -I/usr/include/blkid -g3 -Wall   -c -o
 src/osd/osd.o src/osd/osd.c
In file included from src/osd/../services/wireplumber_service.h:3,
                 from src/osd/osd.c:8:
/usr/include/sys/cdefs.h:4:2: warning: #warning usage of non-standard #include <sys/c
defs.h> is deprecated [-Wcpp]
    4 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^~~~~~~
src/osd/../services/wireplumber_service.h:36:27: error: expected ';' before 'enum'
   36 |     static __always_inline enum WirePlumberServicePortChannel
      |                           ^~~~~
      |                           ;
src/osd/osd.c:29:40: warning: excess elements in array initializer
   29 | static guint osd_signals[signals_n] = {0};
      |                                        ^
src/osd/osd.c:29:40: note: (near initialization for 'osd_signals')
src/osd/osd.c: In function 'osd_dispose':
src/osd/osd.c:34:10: warning: unused variable 'self' [-Wunused-variable]
   34 |     OSD *self = OSD_OSD(gobject);
      |          ^~~~
src/osd/osd.c: At top level:
src/osd/osd.c:29:14: warning: 'osd_signals' defined but not used [-Wunused-variable]
   29 | static guint osd_signals[signals_n] = {0};
      |              ^~~~~~~~~~~
make: *** [<builtin>: src/osd/osd.o] Error 1
```

**Comment by ldelossa** [comment]
@lidgnulinux hmm, it could be... I haven't tested this against `musl` at all. 

But the errors that are breaking make seem more like... gcc is being stricter then on my machine? For example 

```
src/osd/osd.c:29:14: warning: 'osd_signals' defined but not used [-Wunused-variable]
   29 | static guint osd_signals[signals_n] = {0};
      |              ^~~~~~~~~~~
```

I'm not seeing this on my machine even tho I also use -Wall :thinking: 

At the least, I can explore why my machine isn't show me those errors and see if I can make it do so. From there I can clean up at least all these errors discovered in your build process. 

I guess in the meantime you can see if compiling with https://github.com/89luca89/distrobox may work for you?

**Comment by lidgnulinux** [comment]
For musl, it seems can be fixed by adding this : 
```
#if !defined(__GLIBC__)
#include <linux/stddef.h>
#endif
```

Now it can be compiled, but when I try to run it, I get segmentation fault.

**Comment by ldelossa** [comment]
Can you paste the stack trace?

**Comment by lidgnulinux** [comment]
> 
 
Sure, 

```
(gdb) bt
#0  0x00007ffff7fb51ab in strcmp (l=0x0, r=0x5555555bf0b4 "performance") at src/string/strcmp.c:5
#1  0x000055555558c5e6 in power_profiles_service_profile_to_icon (profile=0x0) at src/services/power_profiles_service/power_profiles_service.c:192
#2  0x0000555555574473 in quick_settings_grid_power_profiles_button_layout (self=0x7fffe577a730)
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:34
#3  0x000055555557452a in quick_settings_grid_power_profiles_button_init ()
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:53
#4  0x0000555555573782 in quick_settings_grid_init_layout (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:248
#5  0x0000555555573947 in quick_settings_grid_init (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:297
#6  0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#7  0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#8  0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#9  0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#10 0x0000555555578aaf in quick_settings_init (self=0x7fffe57b9910) at src/panel/quick_settings/quick_settings.c:215
#11 0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#12 0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#13 0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#14 0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#15 0x0000555555578e7f in quick_settings_activate (app=0x7ffff68ecae0, user_data=0x0) at src/panel/quick_settings/quick_settings.c:304
#16 0x0000555555569755 in activate (app=0x7ffff68ecae0, user_data=0x0) at src/main.c:115
#17 0x00007ffff7cbc300 in g_closure_invoke () at /usr/lib//libgobject-2.0.so.0
#18 0x00007ffff7ce99f6 in ??? () at /usr/lib//libgobject-2.0.so.0
#19 0x00007ffff7cdabb2 in ??? () at /usr/lib//libgobject-2.0.so.0
#20 0x00007ffff7cdadd3 in g_signal_emit_valist () at /usr/lib//libgobject-2.0.so.0
#21 0x00007ffff7cdae90 in g_signal_emit () at /usr/lib//libgobject-2.0.so.0
#22 0x00007ffff71ed909 in ??? () at /usr/lib//libgio-2.0.so.0
#23 0x00007ffff71edabc in g_application_run () at /usr/lib//libgio-2.0.so.0
#24 0x00005555555698a5 in main (argc=1, argv=0x7fffffffe938) at src/main.c:145
(gdb) 
```

bt full : 

```
(gdb) bt full
#0  0x00007ffff7fb51ab in strcmp (l=0x0, r=0x5555555bf0b4 "performance") at src/string/strcmp.c:5
#1  0x000055555558c5e6 in power_profiles_service_profile_to_icon (profile=0x0) at src/services/power_profiles_service/power_profiles_service.c:192
#2  0x0000555555574473 in quick_settings_grid_power_profiles_button_layout (self=0x7fffe577a730)
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:34
        power_profiles_service = 0x7ffff3fea170
        active_profile = 0x0
        icon = 0x7f0cc1b9808200cf <error: Cannot access memory at address 0x7f0cc1b9808200cf>
#3  0x000055555557452a in quick_settings_grid_power_profiles_button_init ()
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:53
        self = 0x7fffe577a730
#4  0x0000555555573782 in quick_settings_grid_init_layout (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:248
        pps_button = 0x7fffe57786f0
        nm = 0x7ffff3fec540
        pps = 0x7ffff3fea170
        logind = 0x7fffe5779420
#5  0x0000555555573947 in quick_settings_grid_init (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:297
#6  0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#7  0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#8  0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#9  0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#10 0x0000555555578aaf in quick_settings_init (self=0x7fffe57b9910) at src/panel/quick_settings/quick_settings.c:215
#11 0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#12 0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#13 0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#14 0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#15 0x0000555555578e7f in quick_settings_activate (app=0x7ffff68ecae0, user_data=0x0) at src/panel/quick_settings/quick_settings.c:304
#16 0x0000555555569755 in activate (app=0x7ffff68ecae0, user_data=0x0) at src/main.c:115
        error = <optimized out>
        resource = 0x7ffff40abd70
        provider = 0x7ffff4093540
        seat = 0x7ffff4f58980
        display = 0x7ffff7ca5630
#17 0x00007ffff7cbc300 in g_closure_invoke () at /usr/lib//libgobject-2.0.so.0
#18 0x00007ffff7ce99f6 in ??? () at /usr/lib//libgobject-2.0.so.0
#19 0x00007ffff7cdabb2 in ??? () at /usr/lib//libgobject-2.0.so.0
#20 0x00007ffff7cdadd3 in g_signal_emit_valist () at /usr/lib//libgobject-2.0.so.0
#21 0x00007ffff7cdae90 in g_signal_emit () at /usr/lib//libgobject-2.0.so.0
#22 0x00007ffff71ed909 in ??? () at /usr/lib//libgio-2.0.so.0
#23 0x00007ffff71edabc in g_application_run () at /usr/lib//libgio-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00005555555698a5 in main (argc=1, argv=0x7fffffffe938) at src/main.c:145
        app = 0x7ffff68ecae0
        status = 32767
(gdb) 
```

**Comment by ldelossa** [comment]
@lidgnulinux I moved the previous messages into #9 :)

**Comment by ldelossa** [comment]
Going to close this for now as the makefile has changed considerably. If you still have an issue please reop.
