### ISSUE TITLE
PowerProfilesService causing nil

### ISSUE THREAD

**Issue by ldelossa** [ldelossa/way-shell#9]
> 
 
Sure, 

```
(gdb) bt
#0  0x00007ffff7fb51ab in strcmp (l=0x0, r=0x5555555bf0b4 "performance") at src/string/strcmp.c:5
#1  0x000055555558c5e6 in power_profiles_service_profile_to_icon (profile=0x0) at src/services/power_profiles_service/power_profiles_service.c:192
#2  0x0000555555574473 in quick_settings_grid_power_profiles_button_layout (self=0x7fffe577a730)
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:34
#3  0x000055555557452a in quick_settings_grid_power_profiles_button_init ()
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:53
#4  0x0000555555573782 in quick_settings_grid_init_layout (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:248
#5  0x0000555555573947 in quick_settings_grid_init (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:297
#6  0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#7  0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#8  0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#9  0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#10 0x0000555555578aaf in quick_settings_init (self=0x7fffe57b9910) at src/panel/quick_settings/quick_settings.c:215
#11 0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#12 0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#13 0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#14 0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#15 0x0000555555578e7f in quick_settings_activate (app=0x7ffff68ecae0, user_data=0x0) at src/panel/quick_settings/quick_settings.c:304
#16 0x0000555555569755 in activate (app=0x7ffff68ecae0, user_data=0x0) at src/main.c:115
#17 0x00007ffff7cbc300 in g_closure_invoke () at /usr/lib//libgobject-2.0.so.0
#18 0x00007ffff7ce99f6 in ??? () at /usr/lib//libgobject-2.0.so.0
#19 0x00007ffff7cdabb2 in ??? () at /usr/lib//libgobject-2.0.so.0
#20 0x00007ffff7cdadd3 in g_signal_emit_valist () at /usr/lib//libgobject-2.0.so.0
#21 0x00007ffff7cdae90 in g_signal_emit () at /usr/lib//libgobject-2.0.so.0
#22 0x00007ffff71ed909 in ??? () at /usr/lib//libgio-2.0.so.0
#23 0x00007ffff71edabc in g_application_run () at /usr/lib//libgio-2.0.so.0
#24 0x00005555555698a5 in main (argc=1, argv=0x7fffffffe938) at src/main.c:145
(gdb) 
```

bt full : 

```
(gdb) bt full
#0  0x00007ffff7fb51ab in strcmp (l=0x0, r=0x5555555bf0b4 "performance") at src/string/strcmp.c:5
#1  0x000055555558c5e6 in power_profiles_service_profile_to_icon (profile=0x0) at src/services/power_profiles_service/power_profiles_service.c:192
#2  0x0000555555574473 in quick_settings_grid_power_profiles_button_layout (self=0x7fffe577a730)
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:34
        power_profiles_service = 0x7ffff3fea170
        active_profile = 0x0
        icon = 0x7f0cc1b9808200cf <error: Cannot access memory at address 0x7f0cc1b9808200cf>
#3  0x000055555557452a in quick_settings_grid_power_profiles_button_init ()
    at src/panel/quick_settings/quick_settings_grid/quick_settings_grid_power_profiles/quick_settings_grid_power_profiles.c:53
        self = 0x7fffe577a730
#4  0x0000555555573782 in quick_settings_grid_init_layout (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:248
        pps_button = 0x7fffe57786f0
        nm = 0x7ffff3fec540
        pps = 0x7ffff3fea170
        logind = 0x7fffe5779420
#5  0x0000555555573947 in quick_settings_grid_init (self=0x7fffe5779420) at src/panel/quick_settings/quick_settings_grid/quick_settings_grid.c:297
#6  0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#7  0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#8  0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#9  0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#10 0x0000555555578aaf in quick_settings_init (self=0x7fffe57b9910) at src/panel/quick_settings/quick_settings.c:215
#11 0x00007ffff7ce5d7b in g_type_create_instance () at /usr/lib//libgobject-2.0.so.0
#12 0x00007ffff7ccc4f1 in ??? () at /usr/lib//libgobject-2.0.so.0
#13 0x00007ffff7ccdad7 in g_object_new_with_properties () at /usr/lib//libgobject-2.0.so.0
#14 0x00007ffff7ccea82 in g_object_new () at /usr/lib//libgobject-2.0.so.0
#15 0x0000555555578e7f in quick_settings_activate (app=0x7ffff68ecae0, user_data=0x0) at src/panel/quick_settings/quick_settings.c:304
#16 0x0000555555569755 in activate (app=0x7ffff68ecae0, user_data=0x0) at src/main.c:115
        error = <optimized out>
        resource = 0x7ffff40abd70
        provider = 0x7ffff4093540
        seat = 0x7ffff4f58980
        display = 0x7ffff7ca5630
#17 0x00007ffff7cbc300 in g_closure_invoke () at /usr/lib//libgobject-2.0.so.0
#18 0x00007ffff7ce99f6 in ??? () at /usr/lib//libgobject-2.0.so.0
#19 0x00007ffff7cdabb2 in ??? () at /usr/lib//libgobject-2.0.so.0
#20 0x00007ffff7cdadd3 in g_signal_emit_valist () at /usr/lib//libgobject-2.0.so.0
#21 0x00007ffff7cdae90 in g_signal_emit () at /usr/lib//libgobject-2.0.so.0
#22 0x00007ffff71ed909 in ??? () at /usr/lib//libgio-2.0.so.0
#23 0x00007ffff71edabc in g_application_run () at /usr/lib//libgio-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00005555555698a5 in main (argc=1, argv=0x7fffffffe938) at src/main.c:145
        app = 0x7ffff68ecae0
        status = 32767
(gdb) 
```

_Originally posted by @lidgnulinux in https://github.com/ldelossa/way-shell/issues/5#issuecomment-1974940610_

**Comment by ldelossa** [comment]
@lidgnulinux - lets make this its own issue, not hijacke the makefile one.

**Comment by ldelossa** [comment]
Hey, so I pushed a commit which should fix this. If it does not you can re-open.
